### ISSUE TITLE
Split up tasks?

### ISSUE THREAD

**Issue by mkaminski1988** [supermetrics/php-ext-jsonpath#48]
@crocodele I've been fixing picking out tests to fix at random, and I imagine that could make it difficult for you to take time to work on what you're interested in. Is there a subset of the tests that you want to reserve for yourself?

**Comment by crocodele** [comment]
@mkaminski1988, no big preferences, but I could look at these as a good way to get more familiar with the different parts of your post-rewrite code:
- comparison_filter/034.phpt
- comparison_filter/053.phpt
- comparison_filter/061.phpt
- comparison_filter/066.phpt
- comparison_filter/070.phpt
- comparison_filter/073.phpt
- comparison_filter/074.phpt

Other than that, we could group the remaining tests by similarity – for example comparison_filter/006.phpt and comparison_filter/007.phpt are essentially the same – and create issues here with maybe 6–8 tests per issue. And then self-assign as we start working on them. I should have some more time over the next two weeks. :slightly_smiling_face:

Again, really appreciate all the work you've done and are doing on this! :heart:

**Comment by mkaminski1988** [comment]
Wonderful, sounds like a plan!

> Again, really appreciate all the work you've done and are doing on this! ❤️

My pleasure, and thanks to you for inspiring me to work on this again. :^)

**Comment by crocodele** [comment]
All right, there's issues for all the remaining "expected failure" tests now.

If some of the obscure ones turn out to be very time-consuming to implement or inconsistent with current behavior, I'm more than OK with regarding stuff as "not supported" for the time being, as long they don't cause segfaults or similar.
