### ISSUE TITLE
Handle lone booleans in filter expressions

### ISSUE THREAD

**Issue by crocodele** [supermetrics/php-ext-jsonpath#57]
Would maybe make sense to throw an exception for these?

Fixes for making the following tests pass:

- [ ] comparison_filter/006.phpt: Test filter expression with boolean and operator and value false
- [ ] ~comparison_filter/007.phpt: Test filter expression with boolean and operator and value true~ Moved to https://github.com/supermetrics/php-ext-jsonpath/issues/59
- [ ] ~comparison_filter/009.phpt: Test filter expression with boolean or operator and value false~ Moved to https://github.com/supermetrics/php-ext-jsonpath/issues/59
- [ ] comparison_filter/010.phpt: Test filter expression with boolean or operator and value true

**Comment by mkaminski1988** [comment]
The logic to detect this in the parser would be a bit hairy (it would be similar to [this](https://github.com/supermetrics/php-ext-jsonpath/blob/main/src/jsonpath/parser.c#L125)), so I think it's OK to allow these redundant subexpressions and save ourselves some extra code. 

This is totally legit in PHP (the standard I default to when there's no specification in JSONpath):

```
php > var_dump((10 > 1) && false);
bool(false)
```

Is there a particular reason why you think this warrants an error?

**Comment by crocodele** [comment]
@mkaminski1988, no real reason other than that they indeed are redundant. :slightly_smiling_face: Perfectly fine to allow them, in which case I believe the currently returned results are all correct?

**Comment by mkaminski1988** [comment]
Yup 👍
