### ISSUE TITLE
Handle some more cases of strict comparisons

### ISSUE THREAD

**Issue by crocodele** [supermetrics/php-ext-jsonpath#59]
Probably best to leverage PHP's strict comparison here too.

Fixes for making the following tests pass:

- [x] comparison_filter/007.phpt: Test filter expression with boolean and operator and value true
- [x] comparison_filter/009.phpt: Test filter expression with boolean or operator and value false
- [x] comparison_filter/047.phpt: Test filter expression with greater than
- [x] comparison_filter/048.phpt: Test filter expression with greater than or equal
- [x] comparison_filter/051.phpt: Test filter expression with less than
- [x] comparison_filter/052.phpt: Test filter expression with less than or equal
- [x] comparison_filter/055.phpt: Test filter expression with negation and less than
- [x] comparison_filter/056.phpt: Test filter expression with not equals

**Comment by mkaminski1988** [comment]
@crocodele PHP is a little weird because it has a strict equality check but not a strict greater-than or less-than check.

From the [docs](https://www.php.net/manual/en/language.operators.comparison.php):

> If both operands are numeric strings, or one operand is a number and the other one is a numeric string, then the comparison is done numerically.

For example, in `tests/comparison_filter/047.php`:

Query: `$[?(@.key>42)]`

```php
array(4) {
  [0]=>
  array(1) {
    ["key"]=>
    int(43)
  }
  [1]=>
  array(1) {
    ["key"]=>
    float(42.0001)
  }
  [2]=>
  array(1) {
    ["key"]=>
    int(100)
  }
  [3]=>
  array(1) {
    ["key"]=>
    string(2) "43"
  }
}
```

This result appears to fall in line with PHP's expected behavior:

```bash
php > var_dump("43" > (int)42);
bool(true)
```

If we wanted to do strict comparisons, then we'd need to modify the expected output to exclude the float result:

```diff
array(3) {
  [0]=>
  array(1) {
    ["key"]=>
    int(43)
  }
-  [1]=>
-  array(1) {
-    ["key"]=>
-    float(42.0001)
-  }
  [2]=>
  array(1) {
    ["key"]=>
    int(100)
  }
}
```

What's your opinion on this? I tend to think we should just stick with PHP's default behavior.

**Comment by crocodele** [comment]
@mkaminski1988, ah yes, I didn't think about the lack of a built-in, strict variant of these. My issue is not so much with the numeric strings and floats as with more "unexpected" comparison results such as:

```
php > var_dump(42 > "value");
bool(true)
```

Would an `is_numeric()` check make sense? So if one of the operand is numeric and the other one is not, the comparison would return false.

**Comment by mkaminski1988** [comment]
Yes, that makes sense. I'll implement that check.

**Comment by mkaminski1988** [comment]
I don't see how we can suppress string results when a _negated_ inequality contains a numeric literal operand and a string literal operand by simply doing the type check you suggested.

For example, in `tests/comparison_filter/055.phpt`:

```
$result = $jsonPath->find($data, "$[?(!(@.key<42))]");
```

The negation would have the effect of allowing all string results.

Is there a JSONpath implementation that handles this correctly? My sense is that a solution to this case would be unjustifiably complex, but maybe there's something I'm missing here.

**Comment by mkaminski1988** [comment]
See #78 for in-progress work on strict inequality checks.

**Comment by mkaminski1988** [comment]
Maybe the `evaluate_*` functions could bubble up a sort of `NULL` value that forces `exec_expression` to exclude the result.

**Comment by crocodele** [comment]
What I'm proposing is:

```
(@.key<42) // true for key 41
(@.key<42) // true for key "41"
(@.key<42) // false for key "value"
(@.key>42) // false for key "value"
```

And in all cases the negation would just negate these:

```
(!(@.key<42)) // false for key 41
(!(@.key<42)) // false for key "41"
(!(@.key<42)) // true for key "value"
(!(@.key>42)) // true for key "value"
```

So the comparison between numeric literal operand and array/boolean/non-numeric string operand would always return `false`, and the negation would simply turn that to `true`. Hence comparison_filter/055.phpt contains also the strings in the expected results:

```
[
    ...
    ["key" => "string"],
    ["some" => "value"],
    ....
]
```

Does that make sense?

This is one of those not-too-well-defined cases really, and [the results in different implementations vary](https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_negation_and_less_than.html).

**Comment by mkaminski1988** [comment]
Yup, I think we're on the same page. Thanks
